apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::005669471820:role/default-eks-node-group-20241002170826192900000004
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::005669471820:user/terraform
      username: terraform
      groups:
        - system:masters
    - userarn: arn:aws:iam::005669471820:root
      username: root
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2024-10-02T17:23:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1875"
  uid: b5fedbec-ee96-4b5a-bbc5-0fe453f4416b
