name: Stage Workflow

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

# Set permissions for OpenID connect
permissions:
    id-token: write # This is required for requesting the JWT
    contents: read  # This is required for actions/checkout
    
jobs:
    build:
        uses: ./.github/workflows/build.yml
        secrets: inherit
        with:
          env: stage

    infra:
        needs: build
        uses: ./.github/workflows/infra.yml
        secrets: inherit
        with:
          env: stage

    app:
        needs: infra
        uses: ./.github/workflows/deploy_pulumi.yml
        secrets: inherit
        with:
          env: stage