name: Setup EKS Kubeconfig

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Set permissions for OpenID connect
permissions:
    id-token: write # This is required for requesting the JWT
    contents: read  # This is required for actions/checkout
          
jobs:
  setup-eks:
    runs-on: ubuntu-latest

    concurrency:
        group: deploy
        cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
            version: 2                         # default
            verbose: false                     # default
            arch: amd64   

      - name: Download EKS Kubeconfig
        run: |
          aws eks update-kubeconfig --name showcase --region ${{ secrets.AWS_REGION }}

      - name: Verify Kubeconfig
        run: kubectl get svc

      - name: Prepare Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.3.7
      - name: Setup Terragrunt v0.46.3
        run: |
          sudo wget -q -O /bin/terragrunt "https://github.com/gruntwork-io/terragrunt/releases/download/v0.46.3/terragrunt_linux_amd64"
          sudo chmod +x /bin/terragrunt
          terragrunt -v
        # Run TG
      - name: Init
        working-directory: terragrunt/stage/aws/backstage/data
        run: terragrunt run-all init --terragrunt-non-interactive
      - name: Plan
        # Skip plan for MAIN
        if: github.event_name == 'push' && github.ref != 'refs/heads/main'
        working-directory: terragrunt/stage/aws/backstage/data 
        run: terragrunt run-all plan --terragrunt-non-interactive
      - name: Apply
        # Apply only for MAIN
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: terragrunt/stage/aws/backstage/data
        run: terragrunt run-all apply --terragrunt-non-interactive